Repository thoth-station/amun-api, pull requests merged in 2018-10, with the labels that each got.

#1 Initial project implementation
  .gitignore
  LICENSE
  OWNERS
  Pipfile
  Pipfile.lock
  README.rst
  amun/__init__.py
  amun/api_v1.py
  amun/configuration.py
  amun/core.py
  amun/dockerfile.py
  amun/entrypoint.py
  amun/exceptions.py
  amun/swagger.yaml
  openshift/buildConfig-template.yaml
  openshift/configmap-template.yaml
  openshift/deployment-template.yaml
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectImageStream-template.yaml
  openshift/inspectJob-template.yaml
  openshift/secrets-template.yaml
  openshift/template.yaml
  playbooks/deprovision.retry
  playbooks/deprovision.yaml
  playbooks/provision.retry
  playbooks/provision.yaml
  playbooks/roles/amun/tasks/main.yaml
Labels: approved, size/XXL

#12 Automatic update of dependency thoth-common from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: bot

#10 Image change trigger
  README.rst
  openshift/inspectJob-template.yaml
Labels: approved, size/S

#14 Respect new thoth-common API
  amun/core.py
Labels: size/S

#20 Automatic update of dependency thoth-common from 0.3.7 to 0.3.9
  Pipfile.lock
Labels: bot

#16 Tweaks in Dockerfile generation
  amun/dockerfile.py
Labels: approved, size/S

#15 Remove old TODOs
  amun/api_v1.py
Labels: approved, size/XS

#18 Separate models for swagger-codegen
  amun/swagger.yaml
Labels: size/M

#17 Run inspect-hwinfo and gather hardware information on node
  README.rst
  openshift/inspectJob-template.yaml
  playbooks/roles/amun/tasks/main.yaml
Labels: approved, size/M, size/S

#21 Fix linter failures
  .coafile
  amun/dockerfile.py
  amun/entrypoint.py
  amun/swagger.yaml
  openshift/secrets-template.yaml
  openshift/template.yaml
  playbooks/deprovision.yaml
  playbooks/roles/amun/tasks/main.yaml
Labels: approved, size/L, size/XS

#24 Redeploy API on config change
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#23 Minor fixes in deployment
  playbooks/roles/amun/tasks/main.yaml
Labels: size/M, size/XS

#26 Provide only one status endpoint
  amun/api_v1.py
  amun/swagger.yaml
Labels: approved, size/L

#29 Directly talk to build pod for gathering logs
  amun/api_v1.py
Labels: size/XS

#32 Fix CMD instruction syntax
  amun/dockerfile.py
Labels: approved, size/XS

#28 Fix echoing back parameters
  amun/api_v1.py
Labels: approved, size/XS

#31 Logs reported from OpenShift can be nullable
  amun/swagger.yaml
Labels: approved, size/XS

#36 Automatic update of dependency thoth-common from 0.3.9 to 0.3.10
  Pipfile.lock
Labels: bot

#37 Automatic update of dependency thoth-common from 0.3.10 to 0.3.11
  Pipfile.lock
Labels: bot

#27 Use TLS in route
  openshift/deployment-template.yaml
Labels: approved, size/XS

#30 Be nice with reports to user when job is not ready yet
  amun/api_v1.py
  amun/swagger.yaml
Labels: approved, size/S

#40 Automatic update of dependency requests from 2.19.1 to 2.20.0
  Pipfile.lock
Labels: bot

#42 Automatic update of dependency thoth-common from 0.3.11 to 0.3.12
  Pipfile.lock
Labels: bot

#45 updated to the thoth zuul jobs
  .zuul.yaml
Labels: size/S

#44 changes to use the external thoth-station.amun role
  README.rst
  playbooks/deprovision.yaml
  playbooks/provision.yaml
  playbooks/roles/amun/tasks/main.yaml
  requirements.yaml
Labels: approved, size/L

#46 Add hardware config
  Pipfile.lock
  amun/api_v1.py
  amun/core.py
  amun/swagger.yaml
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectJob-template.yaml
Labels: approved, size/L

#43 Added hardware specification to swagger /inspect
  amun/swagger.yaml
Labels: size/M

#49 Automatic update of dependency thoth-common from 0.3.12 to 0.3.14
  Pipfile.lock
Labels: bot

#52 Automatic update of dependency thoth-common from 0.3.14 to 0.3.16
  Pipfile.lock
Labels: bot
