Repository thoth-station/amun-api, pull requests merged in 2018-11, with the labels that each got.

#56 Automatic update of dependency thoth-common from 0.3.16 to 0.4.0
  Pipfile.lock
Labels: bot

#57 Automatic update of dependency connexion from 1.5.3 to 2.0.0
  Pipfile.lock
Labels: bot

#59 Fix swagger
  amun/swagger.yaml
Labels: approved, size/XS

#65 Automatic update of dependency connexion from 2.0.0 to 2.0.1
  Pipfile.lock
Labels: bot

#66 Automatic update of dependency requests from 2.20.0 to 2.20.1
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency connexion from 2.0.1 to 2.0.2
  Pipfile.lock
Labels: bot

#67 Adjust apiVersion in templates
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectImageStream-template.yaml
Labels: approved, size/S

#74 Automatic update of dependency thoth-common from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#72 Lower memory requests
  openshift/inspectBuildConfig-template.yaml
Labels: approved, size/XS

#68 Use apiVersion as provided by template
  amun/core.py
Labels: approved, size/S, size/XS

#78 Store inspection specification in annotations
  amun/core.py
  openshift/inspectBuildConfig-template.yaml
Labels: size/S

#80 Automatic update of dependency thoth-common from 0.4.2 to 0.4.3
  Pipfile.lock
Labels: bot

#82 Automatic update of dependency thoth-common from 0.4.3 to 0.4.4
  Pipfile.lock
Labels: bot

#83 Fix parameter name
  amun/api_v1.py
Labels: approved, size/XS

#85 Inspection specification is preset in buildconfig
  amun/api_v1.py
Labels: size/XS

#91 Automatic update of dependency thoth-common from 0.4.4 to 0.4.5
  Pipfile.lock
Labels: bot

#92 Explicitly convert stdout to string
  amun/inspect.py
Labels: size/XS

#93 Treat stdout as dict
  amun/swagger.yaml
Labels: size/XS

#94 We do not expect stderr to be a JSON
  amun/inspect.py
Labels: size/XS

#95 Automatic update of dependency pylint from 2.1.1 to 2.2.0
  Pipfile.lock
Labels: bot

#96 Automatic update of dependency pylint from 2.2.0 to 2.2.1
  Pipfile.lock
Labels: bot

#98 Automatic update of dependency thoth-common from 0.4.5 to 0.4.6
  Pipfile.lock
Labels: bot

#99 Automatic update of dependency pylint from 2.2.1 to 2.2.2
  Pipfile.lock
Labels: bot
