Repository thoth-station/amun-api, pull requests merged in 2018-12, with the labels that each got.

#101 Tweaks to make pipenv behave correctly in inspection runs
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
Labels: size/S

#100 Make pipenv behave nicely in inspection builds
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectBuildConfigWithCPU-template.yaml
Labels: size/S

#105 Open stderr reporting file for writing
  amun/inspect.py
Labels: size/XS

#106 Explicitly carry requests with an inspection request
  amun/api_v1.py
Labels: size/S

#108 Automatic update of dependency prometheus-client from 0.4.2 to 0.5.0
  Pipfile.lock
Labels: bot

#109 Automatic update of dependency prometheus-flask-exporter from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#110 Automatic update of dependency requests from 2.20.1 to 2.21.0
  Pipfile.lock
Labels: bot

#111 Automatic update of dependency connexion from 2.0.2 to 2.1.0
  Pipfile.lock
Labels: bot

#107 Register inspection jobs for operator handling events
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
Labels: size/XS

#113 Make sure we trust AICoE index
  amun/dockerfile.py
Labels: size/XS

#116 Automatic update of dependency prometheus-flask-exporter from 0.4.1 to 0.5.1
  Pipfile.lock
Labels: bot

#117 Automatic update of dependency connexion from 2.1.0 to 2.2.0
  Pipfile.lock
Labels: bot
