Repository thoth-station/amun-api, pull requests merged in 2019-02, with the labels that each got.

#132 Update year in sources
  amun/__init__.py
  amun/api_v1.py
  amun/configuration.py
  amun/dockerfile.py
  amun/entrypoint.py
  amun/exceptions.py
  amun/inspect.py
Labels: size/S

#133 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#134 this parameter is not required for this template
  openshift/template.yaml
Labels: approved, size/XS

#135 separated templates by namespace
  openshift/amunApiNamespace-template.yaml
  openshift/amunInspectionNamespace-template.yaml
Labels: approved, size/M

#136 fixing template names
  openshift/amunApiNamespace-template.yaml
  openshift/amunInspectionNamespace-template.yaml
Labels: approved, size/XS

#137 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#141 Automatic update of dependency pylint from 2.2.2 to 2.3.0
  Pipfile.lock
Labels: bot
