Repository thoth-station/amun-api, pull requests merged in 2019-06, with the labels that each got.

#174 Provide default registry for inspection jobs to pull images from
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
Labels: approved, size/XS

#175 Insection typo fixed
  amun/swagger.yaml
Labels: approved, size/S

#176 Capture datetime of an inspection run
  amun/inspect.py
Labels: approved, size/XS

#177 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#178 Automatic update of dependency prometheus-client from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#179 Automatic update of dependency prometheus-flask-exporter from 0.8.0 to 0.8.1
  Pipfile.lock
Labels: bot

#180 Automatic update of dependency connexion from 2.2.0 to 2.3.0
  Pipfile.lock
Labels: bot

#184 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#186 Automatic update of dependency prometheus-client from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#182 Report correct error if no log is found but job exists
  amun/api_v1.py
Labels: approved, size/XS

#183 Update the trigger-build job to use the latest job API
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: size/XS

#187 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#188 Automatic update of dependency prometheus-flask-exporter from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#189 Automatic update of dependency prometheus-flask-exporter from 0.8.2 to 0.9.0
  Pipfile.lock
Labels: bot
