Repository thoth-station/amun-api, pull requests merged in 2019-03, with the labels that each got.

#142 Use Kernel statistics to gather information about CPU utilization
  amun/inspect.py
Labels: approved, do-not-merge/work-in-progress, size/M

#143 Automatic update of dependency prometheus-flask-exporter from 0.5.1 to 0.6.0
  Pipfile.lock
Labels: bot

#144 Automatic update of dependency pylint from 2.3.0 to 2.3.1
  Pipfile.lock
Labels: bot

#145 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#146 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#148 Automatic update of dependency prometheus-flask-exporter from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot
