Repository thoth-station/amun-api, pull requests merged in 2019-10, with the labels that each got.

#238 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#239 Automatic update of dependency opentracing-instrumentation from 3.2.0 to 3.2.1
  Pipfile.lock
Labels: bot

#240 Automatic update of dependency prometheus-flask-exporter from 0.10.0 to 0.11.0
  Pipfile.lock
Labels: bot

#241 Automatic update of dependency grpcio from 1.24.0 to 1.24.1
  Pipfile.lock
Labels: bot

#242 Automatic update of dependency grpcio-tools from 1.24.0 to 1.24.1
  Pipfile.lock
Labels: bot

#244 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#249 Add Thoth-Version header
  amun/entrypoint.py
Labels: approved, size/XS

#251 Automatic update of dependency connexion from 2.3.0 to 2.4.0
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#252 Automatic update of dependency grpcio from 1.24.1 to 1.24.3
  Pipfile.lock
Labels: bot

#253 Automatic update of dependency grpcio-tools from 1.24.1 to 1.24.3
  Pipfile.lock
Labels: bot

#254 Maintain imagestream template for consistency
  openshift/deployment-template.yaml
  openshift/imagestream-template.yaml
Labels: approved, size/M

#255 updated templates with annotations and param thoth-advise-value
  openshift/amunApiNamespace-template.yaml
  openshift/amunInspectionNamespace-template.yaml
  openshift/buildConfig-template.yaml
  openshift/configmap-template.yaml
  openshift/deployment-template.yaml
  openshift/imagestream-template.yaml
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectBuildConfigWithCPU-template.yaml
  openshift/inspectImageStream-template.yaml
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
  openshift/secrets-template.yaml
Labels: approved, size/M

#256 Add an example inspection job output
  README.rst
Labels: approved, size/S
