Repository thoth-station/amun-api, pull requests merged in 2019-04, with the labels that each got.

#149 Automatic update of dependency thoth-common from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#150 Automatic update of dependency prometheus-flask-exporter from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#151 namespace and tag of image to be used are now parameterizable
  openshift/deployment-template.yaml
Labels: approved, size/S

#153 Automatic update of dependency thoth-common from 0.8.2 to 0.8.3
  Pipfile.lock
Labels: bot

#156 Automatic update of dependency thoth-common from 0.8.3 to 0.8.4
  Pipfile.lock
Labels: bot

#158 Automatic update of dependency thoth-common from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#157 added a build trigger to the post pipeline
  .zuul.yaml
Labels: approved, size/XS

#160 Update job templates with imagestream info
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
Labels: approved, size/S

#161 Mark creation time of an inspection run
  amun/api_v1.py
  amun/swagger.yaml
Labels: approved, size/S

#162 Automatic update of dependency prometheus-flask-exporter from 0.7.1 to 0.7.2
  Pipfile.lock
Labels: bot
