Repository thoth-station/amun-api, pull requests merged in 2019-05, with the labels that each got.

#163 Properly install signal handler to obtain CPU stats
  amun/inspect.py
Labels: size/XS

#164 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#165 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: bot

#166 Automatic update of dependency flask from 1.0.2 to 1.0.3
  Pipfile.lock
Labels: bot

#167 Automatic update of dependency prometheus-flask-exporter from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: bot

#168 Automatic update of dependency prometheus-flask-exporter from 0.7.3 to 0.7.4
  Pipfile.lock
Labels: bot

#169 Automatic update of dependency prometheus-flask-exporter from 0.7.4 to 0.8.0
  Pipfile.lock
Labels: bot

#170 updated the image registry to the deployment
  openshift/deployment-template.yaml
Labels: approved
