Repository thoth-station/amun-api, pull requests merged in 2019-07, with the labels that each got.

#190 Automatic update of dependency flask from 1.0.3 to 1.1.0
  Pipfile.lock
Labels: bot

#191 Automatic update of dependency flask from 1.1.0 to 1.1.1
  Pipfile.lock
Labels: bot

#193 Allow empty list of native packages to be passed
  amun/dockerfile.py
Labels: approved, size/XS

#194 Extend Amun specification and docker file
  amun/dockerfile.py
  amun/inspect.py
  amun/swagger.yaml
Labels: approved, size/S

#196 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#197 value: instead of default: in parameters
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
Labels: approved, size/S

#198 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#201 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: size/XS

#202 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#200 Adjust logic for optaining CPU related statistics of the child process
  amun/inspect.py
Labels: approved, size/L, size/M

#203 Remove unused imports
  amun/inspect.py
Labels: approved, size/XS

#204 Introduce user's inspection identifier
  amun/api_v1.py
  amun/swagger.yaml
Labels: approved, size/S

#205 Use process.communicate() to correctly assign return code of the child process
  amun/inspect.py
Labels: approved, size/XS

#206 Propagate empty dict instead of empty string to show related exception
  amun/inspect.py
Labels: approved, size/XS

#207 Automatic update of dependency thoth-common from 0.9.4 to 0.9.5
  Pipfile.lock
Labels: bot

#209 Fix propagation of usage
  amun/inspect.py
Labels: approved, size/XS
