Repository thoth-station/amun-api, pull requests merged in 2019-08, with the labels that each got.

#211 Add usage to the inspection job log schema
  amun/swagger.yaml
Labels: approved, size/XS

#212 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#213 Automatic update of dependency prometheus-flask-exporter from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#215 Remove anchor, use ref instead
  amun/swagger.yaml
Labels: approved, size/XS

#214 State boolean flag update which is already implemented
  amun/swagger.yaml
Labels: approved, size/XS

#216 Add support for supplying environment variables
  amun/dockerfile.py
  amun/swagger.yaml
Labels: approved, size/S

#217 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#218 Stop using extras in thoth-common
  Pipfile
  Pipfile.lock
Labels: size/XL

#219 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#220 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#221 Added config
  .thoth.yaml
Labels: approved, size/S

#222 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#223 Added missing parameters to Amun request
  README.rst
Labels: approved, size/XS
