Repository thoth-station/amun-api, pull requests merged in 2019-01, with the labels that each got.

#118 OpenShift specific logic has been moved to thoth-common
  amun/api_v1.py
  amun/core.py
Labels: size/L

#120 Add missing parameter for scheduling call
  amun/api_v1.py
Labels: size/XS

#121 Be consistent with env variable naming in thoth-common
  amun/configuration.py
Labels: size/XS

#122 Be consistent with env variable naming in thoth-common
  amun/api_v1.py
Labels: size/S

#123 Keep requirements optional
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
Labels: size/XS

#124 Distinguish between build and run requirements when scheduling workload
  amun/api_v1.py
Labels: size/S

#125 Fix env variable names in configuration
  openshift/deployment-template.yaml
Labels: size/XS

#126 Schedule builds as a workload
  amun/api_v1.py
Labels: size/XS

#131 Automatic update of dependency thoth-common from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot
