Repository thoth-station/amun-api, pull requests merged in 2019-12, with the labels that each got.

#273 Automatic update of dependency prometheus-flask-exporter from 0.11.0 to 0.12.0
  Pipfile.lock
Labels: bot, size/M

#274 added the missing modules
  Pipfile
  Pipfile.lock
Labels: size/L

#275 added the missing modules
  Pipfile
  Pipfile.lock
Labels: size/S

#276 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/XS

#277 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/S

#278 Automatic update of dependency sentry-sdk from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#279 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#280 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/M

#281 Automatic update of dependency connexion from 2.4.0 to 2.5.0
  Pipfile.lock
Labels: bot, size/S

#282 Automatic update of dependency grpcio from 1.25.0 to 1.26.0
  Pipfile.lock
Labels: bot, size/L

#283 Automatic update of dependency grpcio-tools from 1.25.0 to 1.26.0
  Pipfile.lock
Labels: bot, size/L

#284 Automatic update of dependency connexion from 2.5.0 to 2.5.1
  Pipfile.lock
Labels: bot, size/S
