Repository thoth-station/amun-api, pull requests merged in 2019-09, with the labels that each got.

#224 Aggregate os information from inspection jobs
  amun/inspect.py
  amun/swagger.yaml
Labels: approved, size/M

#225 Propagate deployment name to deployment
  openshift/deployment-template.yaml
Labels: approved, size/XS

#226 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#227 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#228 Make Amun API OpenAPI v3 compliant
  Pipfile
  Pipfile.lock
  amun/configuration.py
  amun/swagger.yaml
  openapi/openapi.yaml
Labels: approved, size/XXL

#229 Fix function call
  amun/dockerfile.py
Labels: approved, size/XS

#231 Fix description of the request body
  openapi/openapi.yaml
Labels: approved, size/XS

#232 Automatic update of dependency prometheus-flask-exporter from 0.9.1 to 0.9.3
  Pipfile.lock
Labels: bot

#233 Automatic update of dependency prometheus-flask-exporter from 0.9.3 to 0.10.0
  Pipfile.lock
Labels: bot

#234 Automatic update of dependency grpcio from 1.23.0 to 1.24.0
  Pipfile.lock
Labels: bot

#235 Automatic update of dependency grpcio-tools from 1.23.0 to 1.24.0
  Pipfile.lock
Labels: bot

#237 bounced all amun version strings to 0.5.0
  amun/__init__.py
  openapi/openapi.yaml
  openshift/amunApiNamespace-template.yaml
  openshift/amunInspectionNamespace-template.yaml
  openshift/buildConfig-template.yaml
  openshift/configmap-template.yaml
  openshift/deployment-template.yaml
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectBuildConfigWithCPU-template.yaml
  openshift/inspectImageStream-template.yaml
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
  openshift/secrets-template.yaml
Labels: approved, size/L
