Repository thoth-station/amun-api, pull requests merged in 2019-11, with the labels that each got.

#257 Automatic update of dependency grpcio from 1.24.3 to 1.25.0
  Pipfile.lock
Labels: bot

#258 Automatic update of dependency grpcio-tools from 1.24.3 to 1.25.0
  Pipfile.lock
Labels: bot

#259 Standardize output for runtime environment
  amun/inspect.py
Labels: approved, size/S

#260 Add runtime environment
  openapi/openapi.yaml
Labels: approved, size/S, size/XS

#261 Automatic update of dependency gunicorn from 19.9.0 to 20.0.0
  Pipfile.lock
Labels: bot

#262 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#263 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#264 Added newlines after dockerfile update string
  amun/dockerfile.py
Labels: approved, size/S

#266 Automatic update of dependency gunicorn from 20.0.0 to 20.0.2
  Pipfile.lock
Labels: bot, size/S

#267 Automatic update of dependency gunicorn from 20.0.2 to 20.0.3
  Pipfile.lock
Labels: bot, size/S

#268 Automatic update of dependency gunicorn from 20.0.3 to 20.0.4
  Pipfile.lock
Labels: bot, size/M

#269 Automatic update of dependency jaeger-client from 4.1.0 to 4.2.0
  Pipfile.lock
Labels: bot

#270 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#271 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/XS
