Repository thoth-station/amun-api, pull requests merged in 2020-01, with the labels that each got.

#285 Happy new year!
  amun/__init__.py
  amun/api_v1.py
  amun/configuration.py
  amun/dockerfile.py
  amun/entrypoint.py
  amun/exceptions.py
  amun/inspect.py
Labels: approved, size/S

#287 Add missing label for Amun inspection is
  openshift/inspectImageStream-template.yaml
Labels: approved, size/XS

#288 Remove node
  amun/dockerfile.py
  openshift/inspectBuildConfigWithCPU-template.yaml
  openshift/inspectJobWithCPU-template.yaml
Labels: approved, size/M

#289 Correct datatype inspection output
  openapi/openapi.yaml
Labels: approved, size/XS

#290 Add field and correct datatype
  openapi/openapi.yaml
Labels: approved, size/XS

#291 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/M

#292 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#293 Automatic update of dependency sentry-sdk from 0.13.5 to 0.14.0
  Pipfile.lock
Labels: bot, size/S

#294 Remove line (finally)
  openapi/openapi.yaml
Labels: approved, size/XS

#295 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/S

#296 Remove LC_ALL change locale warning
  amun/dockerfile.py
Labels: approved, size/XS

#298 Revert "Remove LC_ALL change locale warning"
  amun/dockerfile.py
Labels: approved, size/XS

#297 Increase memory requiremetns for example input
  openapi/openapi.yaml
Labels: approved, size/XS

#300 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/S

#301 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#302 Automatic update of dependency jaeger-client from 4.2.0 to 4.3.0
  Pipfile.lock
Labels: bot, size/XS

#303 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/S

#304 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#305 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/S

#307 Automatic update of dependency sentry-sdk from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot, size/XS

#308 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#309 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/S

#310 Fix default requests assignment if None was provided on endpoint
  amun/api_v1.py
Labels: approved, size/S

#312 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/S

#313 Force reinstall and upgrade specified Python packages
  amun/dockerfile.py
Labels: approved, size/XS

#315 Automatic update of dependency connexion from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: bot, size/XS

#316 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
