Repository thoth-station/amun-api, pull requests merged in 2020-02, with the labels that each got.

#317 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#318 Automatic update of dependency grpcio from 1.26.0 to 1.27.0
  Pipfile.lock
Labels: bot, size/L

#319 Automatic update of dependency grpcio-tools from 1.26.0 to 1.27.0
  Pipfile.lock
Labels: bot, size/L

#314 Fix escaping of quotes when writing Pipfile.lock
  amun/dockerfile.py
Labels: approved, size/XS

#322 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#323 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/XS

#324 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#326 Automatic update of dependency grpcio from 1.26.0 to 1.27.1
  Pipfile.lock
Labels: bot, size/M

#327 Automatic update of dependency grpcio-tools from 1.26.0 to 1.27.1
  Pipfile.lock
Labels: bot, size/M

#328 Automatic update of dependency prometheus-flask-exporter from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/S

#329 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#330 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#331 Adjust ttl to keep objects longer in the cluster
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectBuildConfigWithCPU-template.yaml
  openshift/inspectImageStream-template.yaml
  openshift/inspectJob-template.yaml
Labels: approved, size/S

#332 Add inspection_id label
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectBuildConfigWithCPU-template.yaml
  openshift/inspectImageStream-template.yaml
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
Labels: approved, size/M

#333 Automatic update of dependency grpcio from 1.27.1 to 1.27.2
  Pipfile.lock
Labels: bot, size/M

#334 Automatic update of dependency grpcio-tools from 1.27.1 to 1.27.2
  Pipfile.lock
Labels: bot, size/M

#335 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/XS

#265 Workflow management
  .coafile
  .yamllint
  Pipfile
  Pipfile.lock
  amun/api_v1.py
  amun/dockerfile.py
  amun/inspect.py
  openapi/openapi.yaml
  openshift/amunApiNamespace-template.yaml
  openshift/amunInspectionNamespace-template.yaml
  openshift/amunInspectionWorkflow-template.yaml
  openshift/amunInspectionWorkflowWithCPU-template.yaml
  openshift/amunRole-template.yaml
  openshift/configmap-template.yaml
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
  playbooks/deprovision.yaml
  playbooks/provision.yaml
  workflows/templates/inspection-build-template.yaml
  workflows/templates/inspection-build-with-cpu-template.yaml
  workflows/templates/inspection-results-template.yaml
  workflows/templates/inspection-run-template.yaml
  workflows/templates/inspection-run-with-cpu-template.yaml
Labels: approved, size/XXL

#339 Changed OUTPUT_ARTIFACT to THOTH_OUTPUT_ARTIFACT
  amun/inspect.py
Labels: approved, size/XS

#338 Removed duplicated function definition
  amun/api_v1.py
Labels: approved, size/M

#340 Fix build issues caused by wrong rebase
  Pipfile.lock
Labels: approved, size/M

#343 Removed InspecitonWorkflowParameters from InspectionResponse
  amun/api_v1.py
  openapi/openapi.yaml
Labels: approved, size/M

#344 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/M

#347 Add micropipenv support
  amun/dockerfile.py
  amun/inspect.py
  openapi/openapi.yaml
Labels: approved, size/S

#349 Virtual environment is a directory
  amun/inspect.py
Labels: size/XS

#346 Fix schema enum used
  openapi/openapi.yaml
Labels: approved, size/XS

#348 Fix dockerfile formatting
  amun/dockerfile.py
Labels: approved, size/XS

#345 Set imagePullPolicy otherwise pull fails on PSI
  workflows/templates/inspection-results-template.yaml
Labels: approved, size/XS

#351 Increase resources for results gathering task
  workflows/templates/inspection-results-template.yaml
Labels: approved, size/XS

#353 No need to create a separate result file, results are part of output
  workflows/templates/inspection-results-template.yaml
Labels: approved, size/XS

#354 Fallback if thoth fails to give advise in bc
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#355 Automatic update of dependency sentry-sdk from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot, size/S

#356 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
