Repository thoth-station/amun-api, pull requests merged in 2020-08, with the labels that each got.

#488 Pass -y on apt-get install
  amun/dockerfile.py
Labels: approved, size/XS

#490 Make default requests configurable via env vars
  amun/api_v1.py
Labels: approved, size/XS

#491 Avoid using echo (bashism)
  amun/dockerfile.py
Labels: approved, size/XS

#493 Automatic update of dependency sentry-sdk from 0.16.2 to 0.16.3
  Pipfile.lock
Labels: approved, bot, size/M

#494 Release of version 0.7.4
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#495 Introduce upgrade pip option
  amun/dockerfile.py
  openapi/openapi.yaml
Labels: size/S

#497 Make black happy
  amun/dockerfile.py
Labels: size/XS

#502 Release of version 0.7.5
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#504 Provide an endpoint for listing available inspections
  amun/api_v1.py
  openapi/openapi.yaml
Labels: approved, size/M

#505 allow amun-api to use printf with valid delimiters
  amun/api_v1.py
  amun/dockerfile.py
Labels: approved, size/XS

#507 Page and limit are optional
  amun/api_v1.py
Labels: approved, size/XS

#508 add delimiter to the write_to_string function
  amun/dockerfile.py
Labels: approved, size/XS

#512 Fix islice serialization
  amun/api_v1.py
Labels: approved, size/S, size/XS

#514 Automatic update of dependency sentry-sdk from 0.16.3 to 0.16.4
  Pipfile.lock
Labels: approved, bot, size/S

#515 Release of version 0.7.6
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/S

#517 Automatic update of dependency sentry-sdk from 0.16.4 to 0.16.5
  Pipfile.lock
Labels: approved, bot, size/M

#519 Fix generation of Dockerfile with pip upgrade
  amun/dockerfile.py
Labels: approved, size/XS

#522 Release of version 0.7.7
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#521 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.1
  Pipfile.lock
Labels: approved, bot, size/XS

#524 Automatic update of dependency thoth-common from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#518 Add support for raw specification
  amun/api_v1.py
Labels: approved, size/M

#526 Release of version 0.8.0
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#529 Make sure the batch_size is always int in raw specification
  amun/api_v1.py
Labels: approved, size/S

#531 Release of version 0.8.1
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#528 Remove unused files
  playbooks/deprovision.yaml
  playbooks/provision.yaml
  requirements.yaml
Labels: approved, size/M

#527 Update README file to reflect the current implementation
  README.rst
  example/inspection-rhtf-conv2d-0f845f38/build/Dockerfile
  example/inspection-rhtf-conv2d-0f845f38/build/log
  example/inspection-rhtf-conv2d-0f845f38/build/specification
  example/inspection-rhtf-conv2d-0f845f38/results/0/hwinfo
  example/inspection-rhtf-conv2d-0f845f38/results/0/log
  example/inspection-rhtf-conv2d-0f845f38/results/0/result
  example/inspection-rhtf-conv2d-0f845f38/results/1/hwinfo
  example/inspection-rhtf-conv2d-0f845f38/results/1/log
  example/inspection-rhtf-conv2d-0f845f38/results/1/result
  example/inspection-rhtf-conv2d-0f845f38/results/2/hwinfo
  example/inspection-rhtf-conv2d-0f845f38/results/2/log
  example/inspection-rhtf-conv2d-0f845f38/results/2/result
  fig/api.gif
  fig/argo_ui.gif
  fig/ceph.gif
Labels: approved, size/XXL

#533 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#532 Perform deep copy of specification to handle escaping correctly
  amun/api_v1.py
Labels: approved, size/M

#536 Release of version 0.9.0
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#537 Automatic update of dependency thoth-storages from 0.25.1 to 0.25.2
  Pipfile.lock
Labels: approved, bot, size/S

#540 Add one more escaped / when serializing files or strings
  amun/dockerfile.py
Labels: approved, size/XS

#542 Release of version 0.9.1
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#543 Include start and end datetime of inspections
  amun/inspect.py
Labels: approved, size/XS

#546 Release of version 0.9.2
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#548 Automatic update of dependency thoth-storages from 0.25.2 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/M

#551 Automatic update of dependency sentry-sdk from 0.16.5 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/S

#550 Propagate Amun version into inspection metadata
  amun/api_v1.py
Labels: approved, size/XS

#554 Automatic update of dependency thoth-common from 0.16.1 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/S

#555 Automatic update of dependency prometheus-flask-exporter from 0.15.4 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/S

#556 Automatic update of dependency flask-cors from 3.0.8 to 3.0.9
  Pipfile.lock
Labels: approved, bot, size/S

#557 Automatic update of dependency sentry-sdk from 0.17.0 to 0.17.1
  Pipfile.lock
Labels: approved, bot, size/S

#559 Automatic update of dependency more-itertools from 8.4.0 to 8.5.0
  Pipfile.lock
Labels: approved, bot, size/S
