Repository thoth-station/amun-api, pull requests merged in 2020-04, with the labels that each got.

#372 Automatic update of dependency thoth-common from 0.12.1 to 0.12.5
  Pipfile.lock
Labels: bot, size/M

#373 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#374 Automatic update of dependency grpcio from 1.27.2 to 1.28.0
  Pipfile.lock
Labels: bot, size/M

#375 Automatic update of dependency grpcio-tools from 1.27.2 to 1.28.0
  Pipfile.lock
Labels: bot, size/M

#378 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#379 Fix key error if build or run are not present in the specification
  amun/api_v1.py
Labels: approved, size/XS

#376 Write results to file not to stdandard output
  amun/inspect.py
  workflows/templates/inspection-results-template.yaml
Labels: approved, size/M

#380 Add missing imports
  amun/api_v1.py
Labels: approved, size/XS

#383 Do not use generateName use inspection id directly
  openshift/amunInspectionWorkflow-template.yaml
  openshift/amunInspectionWorkflowWithCPU-template.yaml
Labels: approved, size/S

#381 Fix variable name, inspection_id is undefined
  amun/api_v1.py
Labels: approved, size/XS

#382 Propagate 404 HTTP status code if the inspection was not found
  amun/api_v1.py
Labels: approved, size/XS

#384 Sync workflow and document IDs
  amun/api_v1.py
  openapi/openapi.yaml
  openshift/amunInspectionWorkflow-template.yaml
  openshift/amunInspectionWorkflowWithCPU-template.yaml
Labels: approved, size/M

#385 workflow_id is undefined
  amun/api_v1.py
Labels: approved, size/XS

#363 Added different function for \n
  amun/dockerfile.py
Labels: approved, size/S

#386 Revert "Write results to file not to stdandard output"
  amun/inspect.py
  workflows/templates/inspection-results-template.yaml
Labels: approved, size/M

#387 Automatic update of dependency flask from 1.1.1 to 1.1.2
  Pipfile.lock
Labels: bot, size/S

#389 Automatic update of dependency grpcio-tools from 1.27.2 to 1.28.1
  Pipfile.lock
Labels: bot, size/M

#390 Automatic update of dependency deprecated from 1.2.7 to 1.2.8
  Pipfile.lock
Labels: bot, size/S

#391 Fix OOM in the s2i build
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#392 Increase memory for the build even more
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#393 Pin grpcio<1.28
  Pipfile
  Pipfile.lock
  openshift/buildConfig-template.yaml
Labels: approved, size/L

#394 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#395 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/M

#396 There is no inspection-sync template
  openshift/amunInspectionWorkflow-template.yaml
Labels: approved, size/S

#397 Add missing parameters to the workflow
  openshift/amunInspectionWorkflow-template.yaml
Labels: approved, size/XS

#399 Remove reference to non-existing template
  openshift/amunInspectionWorkflowWithCPU-template.yaml
Labels: approved, size/S

#398 Create directory structure for results if not exist already
  amun/inspect.py
Labels: approved, size/S

#400 Add missing parameters to the workflow
  openshift/amunInspectionWorkflowWithCPU-template.yaml
Labels: approved, size/XS

#401 Update inspection templates
  amun/api_v1.py
  openapi/openapi.yaml
  openshift/amunInspectionWorkflow-template.yaml
  openshift/amunInspectionWorkflowWithCPU-template.yaml
  workflows/templates/inspection-run-template.yaml
  workflows/templates/inspection-run-with-cpu-template.yaml
Labels: approved, size/M

#404 Make all inspection paths parametrize
  amun/inspect.py
Labels: approved, size/S

#405 Automatic update of dependency thoth-common from 0.12.7 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#406 Automatic update of dependency deprecated from 1.2.8 to 1.2.9
  Pipfile.lock
Labels: bot, size/XS

#407 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#408 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#409 Automatic update of dependency connexion from 2.6.0 to 2.7.0
  Pipfile.lock
Labels: bot, size/XS

#410 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/S

#411 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
