Repository thoth-station/amun-api, pull requests merged in 2020-07, with the labels that each got.

#449 Include pre-commit for amun-api
  .coafile
  .github/CODEOWNERS
  .gitignore
  .pre-commit-config.yaml
  .thothTemplate.yaml
  README.rst
  amun/api_v1.py
  amun/configuration.py
  amun/dockerfile.py
  amun/inspect.py
  pyproject.toml
Labels: approved, size/L

#448 Allow maintainers to release the application
  .thoth.yaml
Labels: approved, size/S

#451 Automatic update of dependency thoth-common from 0.13.13 to 0.14.0
  Pipfile.lock
Labels: approved, bot, size/L

#453 Release of version 0.6.0
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/L

#445 Match results key with adapters
  openshift/configmap-template.yaml
Labels: approved

#457 Automatic update of dependency thoth-common from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/S

#458 Automatic update of dependency sentry-sdk from 0.15.1 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/S

#459 Release of version 0.7.0
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#447 adding support for amun deployment to thoth-app
  openshift/amunApiNamespace-template.yaml
  openshift/amunInspectionNamespace-template.yaml
  openshift/amunInspectionWorkflow-template.yaml
  openshift/amunInspectionWorkflowWithCPU-template.yaml
  openshift/amunRole-template.yaml
  openshift/buildConfig-template.yaml
  openshift/configmap-template.yaml
  openshift/deployment-template.yaml
  openshift/imagestream-template.yaml
  openshift/inspectBuildConfig-template.yaml
  openshift/inspectBuildConfigWithCPU-template.yaml
  openshift/inspectImageStream-template.yaml
  openshift/inspectJob-template.yaml
  openshift/inspectJobWithCPU-template.yaml
  openshift/secrets-template.yaml
  workflows/templates/inspection-build-template.yaml
  workflows/templates/inspection-build-with-cpu-template.yaml
  workflows/templates/inspection-run-template.yaml
  workflows/templates/inspection-run-with-cpu-template.yaml
Labels: approved, do-not-merge/needs-rebase, size/XXL

#460 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/M

#461 Automatic update of dependency prometheus-flask-exporter from 0.14.1 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/M

#462 Automatic update of dependency sentry-sdk from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#467 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/S

#465 Let build to accept null
  openapi/openapi.yaml
Labels: approved, size/XS

#468 Create & expose service version
  amun/api_v1.py
  amun/entrypoint.py
Labels: approved, size/S

#469 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/XS

#471 Release of version 0.7.1
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/S

#472 inspectionstore has attribute build
  amun/api_v1.py
Labels: approved, size/XS

#474 Release of version 0.7.2
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#475 Make started_at nullable
  openapi/openapi.yaml
Labels: approved, size/XS

#480 Automatic update of dependency thoth-storages from 0.24.4 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/L

#479 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/XS

#477 Automatic update of dependency sentry-sdk from 0.16.1 to 0.16.2
  Pipfile.lock
Labels: bot, size/XS

#476 Automatic update of dependency prometheus-flask-exporter from 0.15.0 to 0.15.4
  Pipfile.lock
Labels: bot, size/XS

#483 Release of version 0.7.3
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/S
