Repository thoth-station/amun-api, pull requests merged in 2020-06, with the labels that each got.

#424 Automatic update of dependency prometheus-flask-exporter from 0.13.0 to 0.14.1
  Pipfile.lock
Labels: bot, size/M

#426 Automatic update of dependency more-itertools from 8.3.0 to 8.4.0
  Pipfile.lock
Labels: bot, size/M

#422 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: bot, size/XS

#425 Automatic update of dependency sentry-sdk from 0.14.4 to 0.15.1
  Pipfile.lock
Labels: bot, size/XS

#423 Automatic update of dependency thoth-common from 0.13.8 to 0.13.12
  Pipfile.lock
Labels: bot, size/XS

#430 fix aicoe index
  README.rst
Labels: approved, size/XS

#403 Adjust inspections to use argo for running inspections
  amun/inspect.py
  openshift/amunInspectionWorkflow-template.yaml
  openshift/amunInspectionWorkflowWithCPU-template.yaml
  openshift/configmap-template.yaml
  workflows/templates/inspection-build-template.yaml
  workflows/templates/inspection-build-with-cpu-template.yaml
  workflows/templates/inspection-results-template.yaml
  workflows/templates/inspection-run-template.yaml
  workflows/templates/inspection-run-with-cpu-template.yaml
Labels: approved, do-not-merge/work-in-progress, size/XXL

#432 Add new line after heredoc
  workflows/templates/inspection-build-template.yaml
  workflows/templates/inspection-build-with-cpu-template.yaml
Labels: approved, size/S

#433 Do not print results to pod logs
  amun/inspect.py
Labels: approved, size/XS

#431 Obtain results from Ceph instead of OpenShift API
  amun/api_v1.py
  openapi/openapi.yaml
Labels: approved, size/XL

#434 Introduce Amun version and service version endpoint
  amun/api_v1.py
  openapi/openapi.yaml
Labels: approved, needs-rebase

#441 Automatic update of dependency opentracing-instrumentation from 3.2.1 to 3.3.1
  Pipfile.lock
Labels: approved, bot

#442 Relocked pipfile lock
  Pipfile.lock
Labels: approved

#443 Include thoth-storages to the pipfile
  Pipfile
  Pipfile.lock
Labels: approved

#444 Add missing Ceph credentials
  openshift/deployment-template.yaml
Labels: approved
