Repository thoth-station/amun-api, pull requests merged in 2020-03, with the labels that each got.

#357 Use Thoth's prefix to store output artifacts
  amun/api_v1.py
  openshift/amunInspectionWorkflow-template.yaml
  openshift/configmap-template.yaml
  openshift/deployment-template.yaml
Labels: approved, size/M

#359 Place Dockerfile and specification to inspection artifacts
  openshift/amunInspectionWorkflow-template.yaml
  openshift/amunInspectionWorkflowWithCPU-template.yaml
  workflows/templates/inspection-results-template.yaml
Labels: approved, size/S

#358 Set allowed failures to 0 by default
  openapi/openapi.yaml
Labels: approved, size/XS

#361 Automatic update of dependency prometheus-flask-exporter from 0.12.2 to 0.13.0
  Pipfile.lock
Labels: bot, size/M

#360 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/M

#362 Move workflow manager logic for amun in Openshift class
  amun/api_v1.py
Labels: approved

#365 Remove graph-sync-operator interference from argo workflows
  workflows/templates/inspection-build-template.yaml
  workflows/templates/inspection-build-with-cpu-template.yaml
  workflows/templates/inspection-run-template.yaml
  workflows/templates/inspection-run-with-cpu-template.yaml
Labels: approved, size/S

#366 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot

#367 Automatic update of dependency sentry-sdk from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot

#369 Automatic update of dependency thoth-common from 0.10.12 to 0.12.1
  Pipfile.lock
Labels: bot, size/S

#371 Parameters in Workflow template is not read
  openshift/amunInspectionWorkflow-template.yaml
  openshift/amunInspectionWorkflowWithCPU-template.yaml
Labels: approved
