Repository thoth-station/amun-api, pull requests merged in 2020-09, with the labels that each got.

#565 Automatic update of dependency prometheus-flask-exporter from 0.16.0 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/L

#564 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/L

#568 Automatic update of dependency thoth-common from 0.17.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#569 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/L

#570 Automatic update of dependency sentry-sdk from 0.17.1 to 0.17.8
  Pipfile.lock
Labels: approved, bot, size/L

#567 Propagate deployment-name and Amun API url to specification
  amun/api_v1.py
Labels: approved, size/XS

#572 Automatic update of dependency sentry-sdk from 0.17.8 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/XS

#573 Add a link to YT video with instructions how to deploy Amun
  README.rst
Labels: approved, size/XS
