Repository thoth-station/amun-api, pull requests merged in 2020-11, with the labels that each got.

#580 Automatic update of dependency thoth-common from 0.20.1 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/L

#581 Automatic update of dependency thoth-storages from 0.25.15 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/L

#583 Automatic update of dependency sentry-sdk from 0.18.0 to 0.19.2
  Pipfile.lock
Labels: approved, bot, size/L

#585 Automatic update of dependency more-itertools from 8.5.0 to 8.6.0
  Pipfile.lock
Labels: approved, bot, size/L

#582 Automatic update of dependency toml from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/XS

#590 port to python 38
  .aicoe-ci.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#591 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#592 update .aicoe-yaml
  .aicoe-ci.yaml
Labels: approved, size/XS
