Repository thoth-station/amun-api, pull requests merged in 2022-02, with the labels that each got.

#643 Include issue template for the repo
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, size/M

#647 Remove the unused packages
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#648 set badges for easy access to content
  README.rst
Labels: approved, size/XS

#651 Fix NotFoundExceptionError import
  amun/api_v1.py
Labels: approved, size/XS
