Repository thoth-station/amun-api, pull requests merged in 2022-04, with the labels that each got.

#656 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test

#658 Add runtime_environment and constraints to api schema
  openapi/openapi.yaml
Labels: approved, size/S

#662 Use thoth-s2i image as a default value in api schema
  openapi/openapi.yaml
Labels: approved, size/XS

#671 Specify version range for markupsafe to fix library issues
  Pipfile
  Pipfile.lock
Labels: size/L

#673 Add my username to approvers and maintainers
  .thoth.yaml
  OWNERS
Labels: approved, size/XS

#668 Add Pipfile and Pipfile.lock as example values in schema
  openapi/openapi.yaml
Labels: approved, size/M

#675 Make runtime_environment and constraints optional
  openapi/openapi.yaml
Labels: approved, size/XS

#678 Constraints key is an array
  openapi/openapi.yaml
Labels: size/XS
